name: No Duplicates (CPD)

on:
  push:
    paths:
      - "src/**"
      - "test/**"
  pull_request:
    paths:
      - "src/**"
      - "test/**"

jobs:
  cpd:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Java (required for PMD)
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Download PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.14.0/pmd-bin-7.14.0.zip
          unzip pmd-bin-7.14.0.zip

      - name: Run CPD for duplicates
        run: |
          ./pmd-bin-7.14.0/bin/run.sh cpd \
            --minimum-tokens 25 \
            --language cpp \
            --dir src \
            --dir test \
            --format xml \
            --fail-on-violation \
            --skip-duplicate-files

      - name: Upload CPD report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cpd-report
          path: pmd-bin-7.14.0/bin/report.xml

      - name: Display CPD report (on failure)
        if: failure()
        run: |
          echo "CPD found duplicates:"
          cat pmd-bin-7.14.0/bin/report.xml
